//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozialHeap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answerID { get; set; }
        public Nullable<int> postID { get; set; }
        public string userID { get; set; }
        public Nullable<int> scoreCounter { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public Nullable<bool> seenByOwner { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
