//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozialHeap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Posts = new HashSet<Post>();
            this.Users = new HashSet<User>();
        }
    
        public int groupID { get; set; }
        public string userID { get; set; }
        public string groupName { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string photo { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
