//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozialHeap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Answers = new HashSet<Answer>();
            this.Users = new HashSet<User>();
        }
    
        public int postID { get; set; }
        public string userID { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<int> scoreCounter { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string name { get; set; }
        public string body { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Group Group { get; set; }
        public virtual PostCategory PostCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
