//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozialHeap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public interface IAppDataContext
    {
        IDbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        IDbSet<Answer> Answers { get; set; }
        IDbSet<AspNetRole> AspNetRoles { get; set; }
        IDbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        IDbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        IDbSet<AspNetUser> AspNetUsers { get; set; }
        IDbSet<Group> Groups { get; set; }
        IDbSet<PostCategory> PostCategories { get; set; }
        IDbSet<Post> Posts { get; set; }
        IDbSet<User> Users { get; set; }

        int SaveChanges();
    }


    public partial class SozialheapEntities : DbContext, IAppDataContext
    {
        public SozialheapEntities()
            : base("name=SozialheapEntities")
        {
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        // breytti í IDBSet
        public virtual IDbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual IDbSet<Answer> Answers { get; set; }
        public virtual IDbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual IDbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual IDbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual IDbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual IDbSet<Group> Groups { get; set; }
        public virtual IDbSet<PostCategory> PostCategories { get; set; }
        public virtual IDbSet<Post> Posts { get; set; }
        public virtual IDbSet<User> Users { get; set; }
    }
}
