//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozialHeap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answers = new HashSet<Answer>();
            this.Groups = new HashSet<Group>();
            this.Posts = new HashSet<Post>();
            this.Groups1 = new HashSet<Group>();
            this.Posts1 = new HashSet<Post>();
            this.Users1 = new HashSet<User>();
            this.Users = new HashSet<User>();
        }
    
        public string userID { get; set; }
        public string userName { get; set; }
        public string fullName { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string photo { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<Post> Posts1 { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
